<center><h1><b>Numpy Array Basics</h1></center>

## 1) Importing Required libraries

In [158]:
#Importing Libraries
import numpy as np
import sys

## 2) Creating and Inspecting a 1-D NumPy Array 

In [159]:
#1D array
x = np.array([1,2,5,6,57,])
print(x.shape)
print(type(x))

(5,)
<class 'numpy.ndarray'>


## 3) Creating and Inspecting a 2-D NumPy Array

In [160]:
#2D array
a = np.array([[1,2],[2,4],[4,7]])
print(a.shape)

(3, 2)


## 4) Creating and Inspecting a 3-D NumPy Array

In [161]:
#3D Array:
n = np.array([[[1,2],[4,6]],[[4,5],[8,9]]])
print(n.shape)

(2, 2, 2)


## 5) Creating and Inspecting a 4-D NumPy Array with Random Integers

In [162]:
#4D Array:
import random
d4 = np.random.randint(1,10,size=(2,3,4,4))
print(d4)
print(d4.shape)

[[[[8 3 7 6]
   [6 3 8 4]
   [3 2 3 1]
   [8 5 3 6]]

  [[5 7 2 4]
   [4 7 7 1]
   [2 7 2 3]
   [5 2 6 2]]

  [[4 8 7 8]
   [4 8 9 8]
   [8 1 9 6]
   [6 4 3 7]]]


 [[[9 4 3 5]
   [2 9 5 8]
   [3 7 2 7]
   [7 2 4 7]]

  [[3 1 7 9]
   [3 5 6 6]
   [3 5 9 2]
   [6 1 5 1]]

  [[9 8 4 1]
   [2 7 8 7]
   [5 7 7 6]
   [5 2 3 2]]]]
(2, 3, 4, 4)


## 6) Creating and Inspecting Another 4-D NumPy Array

In [163]:
#4-D Array (Shape 2×2×2×2)
d = np.random.randint(1,10,size=(2,2,2,2))
print(d)
print(d.shape)

[[[[1 4]
   [8 5]]

  [[5 5]
   [4 7]]]


 [[[1 2]
   [1 6]]

  [[9 6]
   [3 8]]]]
(2, 2, 2, 2)


## 7) Array multiplication

In [164]:
#List vs NumPy Array Multiplication
list1 = [1,2,3]
list2 = np.array([1,2,3])
print(list1*2)
print(list2*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


## 8) Array Properties and Changing Data Type

In [165]:
#Inspecting NumPy Array Properties and Changing Data Type
ab = np.array([1,2,3])
print(ab.ndim)
print(ab.size)
print(ab.dtype)
print(ab.astype('U64'))

1
3
int64
['1' '2' '3']


## 9) Array Properties and Changing Data Type

In [166]:
#2-D NumPy Array Attributes and Type Conversion
ba = np.array([[1,3],[4,5]])
print(ba.ndim)
print(ba.size)
print(ba.dtype)
print(ba.astype('float64'))

2
4
int64
[[1. 3.]
 [4. 5.]]


## 10) Array Properties and Changing Data Type

In [167]:
#3-D NumPy Array Attributes and Type Conversion
c = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c.ndim)
print(c.size)
print(c.dtype)
print(c.astype('float64'))

3
8
int64
[[[1. 2.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


## 11) Memory Size of Python List Elements

In [168]:
#Memory Size of Python List Elements
s = [0,1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(s))
print(sys.getsizeof(s)*len(s))

136
1360


## 12) Item Size and Total Memory Usage

In [169]:
#Inspecting Item Size and Total Memory Usage of a NumPy Array
di = np.array([0,1,2,3,4,5,6,7,8,9])
print(di.itemsize)
print(di.size*di.itemsize)

8
80


## 13) Performance Comparison

In [170]:
#Performance Comparison: Lists vs NumPy Arrays
import time
size = 10000
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)
initialTime = time.time()
resultantList = [(a*b) for a,b in zip(list1,list2)]
print(time.time() - initialTime)
initialTime = time.time()
resultantArray = array1 * array2
print((time.time() - initialTime))

0.006717205047607422
0.0003521442413330078


## 14) Arrays Filled with Zeros

In [171]:
#Creating NumPy Arrays Filled with Zeros
xy = np.zeros((2,3))
yz = np.zeros((3,3),dtype=int)
print(xy)
print(yz)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 15) Arrays Filled with Ones and Checking Data Type

In [172]:
#Creating NumPy Arrays Filled with Ones and Checking Data Type
g = np.ones((2,3))
print(c.dtype)
h = np.ones((3,3),dtype=int)
print(g)
print(h)

int64
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## 16) Array Filled with a Specific Value

In [173]:
#Creating a NumPy Array Filled with a Specific Value
g = np.full((3,3),30)
print(g)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


## 17) Identity Matrix

In [174]:
#NumPy Identity Matrix Example
a = np.identity(4)
print(a)
print(type(a))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>


## 18) Python List to NumPy Array

In [175]:
#Converting Python List to NumPy Array
a = [1,2,3,4,5]
x = np.asarray(a)
x

array([1, 2, 3, 4, 5])

## 19) Python Tuple to NumPy Array

In [176]:
#Converting Python Tuple to NumPy Array
a = (1,2,3)
x = np.asarray(a)
x

array([1, 2, 3])

## 20) NumPy Array with arange() and Slicing Elements

In [177]:
#Creating a Array with arange() and Slicing Elements
a = np.arange(10)
print(a[2:8])

[2 3 4 5 6 7]


## 21) Array of Random Floats

In [178]:
#Creating a 1-D NumPy Array of Random Floats
a = np.random.random(10)
print(a)

[0.98330707 0.6498707  0.88077529 0.10574053 0.55603892 0.60451182
 0.80701092 0.14599214 0.3108198  0.32067089]


## 22) Slicing a NumPy Array with a Step

In [179]:
#Slicing a NumPy Array with a Step
a[::2]

array([0.98330707, 0.88077529, 0.55603892, 0.80701092, 0.3108198 ])

### 23) Slicing a NumPy Array with Start, Stop, and Step

In [180]:
#Slicing a NumPy Array with Start, Stop, and Step
a[2:10:2]

array([0.88077529, 0.55603892, 0.80701092, 0.3108198 ])

## 24) Slicing a NumPy Array with a Custom Step Size

In [181]:
#Slicing a NumPy Array with a Custom Step Size
a[2:10:5]

array([0.88077529, 0.14599214])

## 25) Accessing a Specific Element

In [182]:
#Accessing a Specific Element in a 2-D NumPy Array
a = np.array([[1,2,3],[4,5,6]])
print(a[0,2])
print(a[1,2])

3
6


## 26) Selecting Specific Rows and Columns

In [183]:
#Selecting Specific Rows and Columns from a 2-D NumPy Array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0:2])
print(a[0:2,-1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[3]
 [6]]


## 27) Selecting Blocks and Rows

In [184]:
#Selecting Blocks and Rows from a 3-D NumPy Array
a = np.array([[[1,2],[2,3],[4,5]],[[6,7],[8,9],[10,11]],[[12,13],[14,15],[16,17]]])
print(a)
print(a[0:2])
print(a[0:1,0:])

[[[ 1  2]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[[[ 1  2]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[1 2]
  [2 3]
  [4 5]]]


## 28) Random Integer NumPy Array

In [185]:
#Random Integer NumPy Array
a = np.array(np.random.randint(10,50,(3,8)))
print(a)

[[43 35 45 25 25 32 19 41]
 [28 29 39 47 49 41 40 13]
 [48 10 38 16 27 11 42 12]]


## 29) Transposing a NumPy Array

In [186]:
#Transposing a NumPy Array
x = np.transpose(a)
print(x)

[[43 28 48]
 [35 29 10]
 [45 39 38]
 [25 47 16]
 [25 49 27]
 [32 41 11]
 [19 40 42]
 [41 13 12]]


## 30) Reshaping a NumPy Array

In [187]:
#Reshaping a NumPy Array into a New Shape
b = (2,4,3)
z = np.reshape(x,b)
print(z)

[[[43 28 48]
  [35 29 10]
  [45 39 38]
  [25 47 16]]

 [[25 49 27]
  [32 41 11]
  [19 40 42]
  [41 13 12]]]


## 31) Array of Random Integers

In [188]:
#Creating a 3-D NumPy Array of Random Integers
a = np.array(np.random.randint(10,50,(2,4,6)))
print(a)

[[[49 39 36 39 24 14]
  [43 38 31 33 12 45]
  [40 11 32 39 28 34]
  [27 45 43 38 17 23]]

 [[37 32 28 35 11 35]
  [13 34 11 49 34 49]
  [33 28 30 11 28 47]
  [32 34 25 30 48 45]]]


## 32) Resizing a 3-D NumPy Array

In [189]:
#Resizing a 3-D NumPy Array from (2×4×6) to (4×3×6)
b = (4,3,6)
ans = np.resize(a,b)
print(ans)

[[[49 39 36 39 24 14]
  [43 38 31 33 12 45]
  [40 11 32 39 28 34]]

 [[27 45 43 38 17 23]
  [37 32 28 35 11 35]
  [13 34 11 49 34 49]]

 [[33 28 30 11 28 47]
  [32 34 25 30 48 45]
  [49 39 36 39 24 14]]

 [[43 38 31 33 12 45]
  [40 11 32 39 28 34]
  [27 45 43 38 17 23]]]


## 33) Flattening a NumPy Array

In [190]:
#Flattening a NumPy Array into 1-D
ans.flatten()

array([49, 39, 36, 39, 24, 14, 43, 38, 31, 33, 12, 45, 40, 11, 32, 39, 28,
       34, 27, 45, 43, 38, 17, 23, 37, 32, 28, 35, 11, 35, 13, 34, 11, 49,
       34, 49, 33, 28, 30, 11, 28, 47, 32, 34, 25, 30, 48, 45, 49, 39, 36,
       39, 24, 14, 43, 38, 31, 33, 12, 45, 40, 11, 32, 39, 28, 34, 27, 45,
       43, 38, 17, 23], dtype=int32)