<center><h1><b>NumPy Task</center>

## Importing NumPy Libaray 

In [42]:
#Importing NumPy Libaray
import numpy as np

## 1) Create a NumPy array of zeros of size 5.

In [43]:
#Create a NumPy array of zeros of size 5.
a_zeros = np.zeros(5)
print(a_zeros)

[0. 0. 0. 0. 0.]


## 2) Create a NumPy array of ones of size 4 × 4.

In [44]:
#Create a NumPy array of ones of size 4 × 4.
a_ones = np.ones((4,4))
print(a_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 3) Create an array of even numbers from 2 to 20.

In [45]:
#Create an array of even numbers from 2 to 20.
even = np.arange(2,21,2)
print(even)

[ 2  4  6  8 10 12 14 16 18 20]


## 4) Create an array with values from 10 to 50, step 5

In [46]:
#Create an array with values from 10 to 50, step 5
a_array = np.arange(10,51,5)
print(a_array)

[10 15 20 25 30 35 40 45 50]


## 5) Create an array [1, 2, 3] and multiply it by 3.

In [47]:
#Array Operations
#Create an array [1, 2, 3] and multiply it by 3.
mul = np.array([1,2,3])
print(mul*3)

[3 6 9]


## 6) Create two arrays and add them element-wise

In [48]:
#Create two arrays and add them element-wise
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
result = array1 + array2
print(result)

[5 7 9]


## 7) Create an array [10, 20, 30, 40] and find its mean.

In [49]:
#Create an array [10, 20, 30, 40] and find its mean.
a = np.array([10, 20, 30, 40])
ans = np.mean(a)
print(ans)

25.0


## 8) Create an array [4, 9, 16, 25] and find the square root.

In [50]:
#Create an array [4, 9, 16, 25] and find the square root.
x = np.array([4, 9, 16, 25])
x_ = np.sqrt(x)
print(x_)

[2. 3. 4. 5.]


## 9) Create a random array of size 5 and find its sum.

In [51]:
#Create a random array of size 5 and find its sum.
rand = np.random.rand(5)
print(rand)
rand_ = np.sum(rand)
print(rand_)

[0.02967263 0.6171351  0.63694894 0.66722708 0.52580422]
2.4767879799768933


## 10) Slice the first 5 elements from an array of numbers from 1 to 10

In [52]:
#Indexing & Slicing:
#Slice the first 5 elements from an array of numbers from 1 to 10
sli = np.arange(1,11)
print(sli[:5])

[1 2 3 4 5]


## 11) Get the last two elements of [10, 20, 30, 40, 50]

In [53]:
#Get the last two elements of [10, 20, 30, 40, 50]
last_two = np.array([10, 20, 30, 40, 50])
print(last_two[3:])

[40 50]


## 12) Change the 3rd element of [1, 2, 3, 4, 5] to 99.

In [54]:
#Change the 3rd element of [1, 2, 3, 4, 5] to 99.
a = np.array([1, 2, 3, 4, 5])
a[1] = 99
print(a)

[ 1 99  3  4  5]


## 13) Create a 3×3 matrix and access the element in the 2nd row, 3rd column.

In [55]:
#Create a 3×3 matrix and access the element in the 2nd row, 3rd column.
mat = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
element = mat[1,2]
print(element)

6


## 14) Create a 1D array and reverse it using slicing.

In [56]:
#Create a 1D array and reverse it using slicing.
rev = np.array([1,2,3,4,5])
rev_ = rev[::-1]
print(rev_)

[5 4 3 2 1]


## 15) Generate a random integer between 1 and 100.

In [57]:
#Random Numbers
#Generate a random integer between 1 and 100.
rand_int = np.random.randint(1,101)
print(rand_int)

88


## 16) Generate a random array of size 3 × 3.

In [58]:
#Generate a random array of size 3 × 3.
rand_array = np.random.rand(3,3)
print(rand_array)

[[0.02303509 0.24575184 0.64834966]
 [0.99639329 0.36853929 0.19237767]
 [0.10832824 0.71676567 0.42001141]]


## 17) Generate 5 random numbers from a normal distribution.

In [59]:
#Generate 5 random numbers from a normal distribution.
num = np.random.randn(5)
print(num)

[ 0.00668081 -1.21981172  0.35901713  1.2574181   0.59683835]


## 18) Generate 10 random numbers between 0 and 1.

In [60]:
#Generate 10 random numbers between 0 and 1.
a = np.random.random(10)
print(a)

[0.69630379 0.29877559 0.74593551 0.97667712 0.41552569 0.41886168
 0.40330708 0.58242415 0.30501925 0.01240653]


## 19) Shuffle an array [1, 2, 3, 4, 5] randomly.

In [62]:
#Shuffle an array [1, 2, 3, 4, 5] randomly.
num = np.array([1, 2, 3, 4, 5])
np.random.shuffle(num)
print(num)

[4 5 2 1 3]
